import { PrismaClient } from './generated/prisma';
import { SubjectPlanConfigData } from './subjects/subjectPlan';

export const DEFAULT_CHINESE_PLAN: SubjectPlanConfigData = {
  tracks: [
    {
      id: 'school',
      name: '校内基础线',
      color: '#3b82f6',
      description: '跟随学校进度，用教辅巩固字词、句式、校内阅读',
    },
    {
      id: 'extensiveReading',
      name: '现代文泛读积累线',
      color: '#14b8a6',
      description: '绘本、桥梁书、儿童文学、报刊时文，积累阅读量',
    },
    {
      id: 'intensiveReading',
      name: '现代文精读线',
      color: '#8b5cf6',
      description: '整本书精读、阅读理解训练、答题规范',
    },
    {
      id: 'output',
      name: '输出表达线',
      color: '#f43f5e',
      description: '口语复述、课堂表达、自我介绍、即兴问答、写作',
    },
    {
      id: 'classical',
      name: '古文线',
      color: '#f59e0b',
      description: '小古文、文言词汇、文言文阅读',
    },
    {
      id: 'poetry',
      name: '诗词线',
      color: '#ec4899',
      description: '古诗背诵、诗词理解、古诗文大会',
    },
  ],
  timeAxis: [
    { label: '2025 暑假', position: 0 },
    { label: '一上', position: 10 },
    { label: '一下', position: 20 },
    { label: '二上', position: 30 },
    { label: '二下', position: 40 },
    { label: '三上', position: 50 },
    { label: '三下', position: 60 },
    { label: '四上', position: 70 },
    { label: '四下', position: 80 },
    { label: '五上', position: 90 },
    { label: '三公', position: 100 },
  ],
  nodes: [
    // 校内基础线
    {
      id: 'c-school-1',
      trackId: 'school',
      label: '字词巩固',
      position: 10,
      time: '2025.09',
      detail: '跟随课内进度，每天 15 分钟字词练习，夯实笔画、笔顺和常用字',
    },
    {
      id: 'c-school-2',
      trackId: 'school',
      label: '默写能手',
      position: 30,
      time: '2026.09',
      detail: '系统默写训练，错别字整理，校内基础知识不丢分',
    },
    {
      id: 'c-school-3',
      trackId: 'school',
      label: '阅读基础题',
      position: 50,
      time: '2027.09',
      detail: '掌握课内阅读理解题型，学会定位信息和规范作答',
    },
    {
      id: 'c-school-4',
      trackId: 'school',
      label: '答题规范',
      position: 70,
      time: '2028.09',
      detail: '阅读答题模板化，作文审题不跑题，校内成绩稳定优秀',
    },
    {
      id: 'c-school-5',
      trackId: 'school',
      label: '综合复习',
      position: 90,
      time: '2028.09',
      detail: '系统梳理小学语文知识点，查漏补缺，为三公鸡尾酒简历打底',
    },

    // 现代文泛读积累线
    {
      id: 'c-extensive-1',
      trackId: 'extensiveReading',
      label: '绘本/桥梁书',
      position: 10,
      time: '2025.09',
      detail: '培养阅读兴趣，每天亲子共读或自主阅读 30 分钟',
    },
    {
      id: 'c-extensive-2',
      trackId: 'extensiveReading',
      label: '儿童文学',
      position: 30,
      time: '2026.09',
      detail: '章节书、儿童文学，保持阅读量，拓宽知识面',
    },
    {
      id: 'c-extensive-3',
      trackId: 'extensiveReading',
      label: '名著 simplified',
      position: 50,
      time: '2027.09',
      detail: '选择适合年龄的名著 simplified 版，积累人文素养',
    },
    {
      id: 'c-extensive-4',
      trackId: 'extensiveReading',
      label: '报刊时文',
      position: 70,
      time: '2028.09',
      detail: '接触新闻、科普、历史类文章，为面谈积累素材',
    },
    {
      id: 'c-extensive-5',
      trackId: 'extensiveReading',
      label: '综合阅读',
      position: 90,
      time: '2028.09',
      detail: '保持高强度泛读，关注社会热点，提升信息获取能力',
    },

    // 现代文精读线
    {
      id: 'c-intensive-1',
      trackId: 'intensiveReading',
      label: '亲子共读',
      position: 10,
      time: '2025.09',
      detail: '低年级以兴趣为主，通过提问引导孩子理解故事',
    },
    {
      id: 'c-intensive-2',
      trackId: 'intensiveReading',
      label: '读书笔记',
      position: 30,
      time: '2026.09',
      detail: '学会摘抄好词好句，写简单的读后感和人物分析',
    },
    {
      id: 'c-intensive-3',
      trackId: 'intensiveReading',
      label: '精读训练',
      position: 50,
      time: '2027.09',
      detail: '阅读理解专项训练，掌握主旨、结构、修辞等答题方法',
    },
    {
      id: 'c-intensive-4',
      trackId: 'intensiveReading',
      label: '整本书精读',
      position: 70,
      time: '2028.09',
      detail: '精读 2-3 本名著，能分析人物、主题和写作手法',
    },
    {
      id: 'c-intensive-5',
      trackId: 'intensiveReading',
      label: '真题训练',
      position: 90,
      time: '2028.09',
      detail: '接触小升初真题，限时训练，提升应试阅读能力',
    },

    // 输出表达线
    {
      id: 'c-output-1',
      trackId: 'output',
      label: '看图说话',
      position: 10,
      time: '2025.09',
      detail: '能根据图片讲清楚时间、地点、人物、事件',
    },
    {
      id: 'c-output-2',
      trackId: 'output',
      label: '100字短文',
      position: 30,
      time: '2026.09',
      detail: '从看图写话过渡到短文，句子通顺、结构完整',
    },
    {
      id: 'c-output-3',
      trackId: 'output',
      label: '300字作文',
      position: 50,
      time: '2027.09',
      detail: '掌握记叙文结构，能写出有细节、有情感的作文',
    },
    {
      id: 'c-output-4',
      trackId: 'output',
      label: '观点写作',
      position: 70,
      time: '2028.09',
      detail: '能针对话题表达观点，论据清楚，逻辑有条理',
    },
    {
      id: 'c-output-5',
      trackId: 'output',
      label: '面谈表达',
      position: 100,
      time: '2029.05',
      detail: '自我介绍、即兴问答、观点表达流利自信',
    },

    // 古文线
    {
      id: 'c-classical-1',
      trackId: 'classical',
      label: '小古文启蒙',
      position: 40,
      time: '2027.02',
      detail: '接触简短小古文，培养语感，积累常见文言词汇',
    },
    {
      id: 'c-classical-2',
      trackId: 'classical',
      label: '小古文 50篇',
      position: 60,
      time: '2027.09',
      detail: '系统学习 50 篇小古文，理解词义和句式',
    },
    {
      id: 'c-classical-3',
      trackId: 'classical',
      label: '文言文阅读',
      position: 80,
      time: '2028.09',
      detail: '能独立阅读浅显文言文，掌握实词、虚词和翻译技巧',
    },
    {
      id: 'c-classical-4',
      trackId: 'classical',
      label: '古文活用',
      position: 100,
      time: '2029.05',
      detail: '能在写作和面谈中引用古文，提升表达深度',
    },

    // 诗词线
    {
      id: 'c-poetry-1',
      trackId: 'poetry',
      label: '古诗启蒙',
      position: 10,
      time: '2025.09',
      detail: '每周 1-2 首古诗，熟读成诵，感受韵律',
    },
    {
      id: 'c-poetry-2',
      trackId: 'poetry',
      label: '75+80 背诵',
      position: 30,
      time: '2026.09',
      detail: '系统背诵小学必背古诗，理解诗意和作者背景',
    },
    {
      id: 'c-poetry-3',
      trackId: 'poetry',
      label: '古诗文大会',
      position: 60,
      time: '2027.11',
      detail: '四年级开始参赛，目标进入复赛/决赛',
    },
    {
      id: 'c-poetry-4',
      trackId: 'poetry',
      label: '诗词赏析',
      position: 80,
      time: '2028.09',
      detail: '能赏析诗词的意境、手法和情感',
    },
    {
      id: 'c-poetry-5',
      trackId: 'poetry',
      label: '面谈引用',
      position: 100,
      time: '2029.05',
      detail: '能在面谈中恰当引用诗句表达观点',
    },
  ],
  keyAchievements: {
    school: [
      {
        time: '一上期末',
        keyword: '字词过关',
        detail: '常用字会认会写，错别字率低于 5%，校内语文成绩稳定优秀。',
      },
      {
        time: '二上期末',
        keyword: '默写扎实',
        detail: '系统默写训练，错别字整理成册，校内基础知识不丢分。',
      },
      {
        time: '三上期末',
        keyword: '阅读基础题过关',
        detail: '掌握课内阅读理解题型，学会定位信息和规范作答。',
      },
      {
        time: '四上期末',
        keyword: '答题规范成型',
        detail: '阅读答题模板化，作文审题不跑题，校内成绩保持前列。',
      },
      {
        time: '五上期末',
        keyword: '综合复习完成',
        detail: '系统梳理小学语文知识点，查漏补缺，简历素材齐全。',
      },
      {
        time: '三公前',
        keyword: '校内成绩无短板',
        detail: '五年级下保持全优，校内荣誉和成绩为面谈打底。',
      },
    ],
    extensiveReading: [
      {
        time: '一上期末',
        keyword: '阅读兴趣养成',
        detail: '绘本、桥梁书自由阅读，全年阅读量 30 本以上。',
      },
      {
        time: '二上期末',
        keyword: '儿童文学入门',
        detail: '章节书、儿童文学持续阅读，拓宽知识面。',
      },
      {
        time: '三上期末',
        keyword: '名著 simplified 积累',
        detail: '选择适合年龄的名著 simplified 版，积累人文素养。',
      },
      {
        time: '四上期末',
        keyword: '报刊时文涉猎',
        detail: '接触新闻、科普、历史类文章，为面谈积累素材。',
      },
      {
        time: '五上期末',
        keyword: '综合阅读稳定',
        detail: '保持高强度泛读，关注社会热点，提升信息获取能力。',
      },
      {
        time: '三公前',
        keyword: '面谈素材充足',
        detail: '阅读面广，能围绕热点、人文话题即兴表达。',
      },
    ],
    intensiveReading: [
      {
        time: '一上期末',
        keyword: '亲子共读转自主',
        detail: '能独立复述故事，回答人物和情节问题。',
      },
      { time: '二上期末', keyword: '读书笔记起步', detail: '学会摘抄好词好句，写简单读后感。' },
      {
        time: '三上期末',
        keyword: '精读方法建立',
        detail: '掌握主旨、结构、修辞等答题方法，阅读专项训练见成效。',
      },
      {
        time: '四上期末',
        keyword: '整本书精读输出',
        detail: '精读 2-3 本名著，能分析人物、主题和写作手法。',
      },
      {
        time: '五上期末',
        keyword: '真题限时训练',
        detail: '接触小升初真题，限时训练，应试阅读能力稳定。',
      },
      { time: '三公前', keyword: '阅读压轴拿分', detail: '复杂文本阅读不怵，答题规范、速度快。' },
    ],
    output: [
      {
        time: '一上期末',
        keyword: '看图说话流利',
        detail: '能根据图片讲清楚时间、地点、人物、事件。',
      },
      {
        time: '二上期末',
        keyword: '100字短文通顺',
        detail: '从看图写话过渡到短文，句子通顺、结构完整。',
      },
      {
        time: '三上期末',
        keyword: '300字作文成型',
        detail: '掌握记叙文结构，能写出有细节、有情感的作文。',
      },
      {
        time: '四上期末',
        keyword: '观点表达清晰',
        detail: '能针对话题表达观点，论据清楚，逻辑有条理。',
      },
      { time: '五上期末', keyword: '面谈素材储备', detail: '自我介绍、常见话题有稿子，表达自然。' },
      { time: '三公前', keyword: '面谈表达自信', detail: '即兴问答、观点表达流利自信，临场不怯。' },
    ],
    classical: [
      {
        time: '二上期末',
        keyword: '小古文启蒙',
        detail: '接触简短小古文，培养语感，积累常见文言词汇。',
      },
      {
        time: '三上期末',
        keyword: '小古文 50篇',
        detail: '系统学习 50 篇小古文，理解词义和句式。',
      },
      {
        time: '四上期末',
        keyword: '文言文阅读独立',
        detail: '能独立阅读浅显文言文，掌握实词、虚词和翻译技巧。',
      },
      { time: '五上期末', keyword: '古文活用', detail: '能在写作和面谈中引用古文，提升表达深度。' },
      { time: '三公前', keyword: '古文面谈加分', detail: '古文积累成为面谈亮点，能恰当引用。' },
    ],
    poetry: [
      {
        time: '一上期末',
        keyword: '古诗启蒙 30首',
        detail: '每周 1-2 首古诗，熟读成诵，感受韵律。',
      },
      {
        time: '二上期末',
        keyword: '75+80 背诵过半',
        detail: '系统背诵小学必背古诗，理解诗意和作者背景。',
      },
      {
        time: '三上期末',
        keyword: '诗词理解进阶',
        detail: '能简单赏析诗词意境，了解作者和创作背景。',
      },
      {
        time: '四上期末',
        keyword: '古诗文大会冲刺',
        detail: '参赛并冲刺复赛，积累文学常识。',
        milestones: ['古诗文大会初赛', '古诗文大会复赛'],
      },
      { time: '五上期末', keyword: '诗词活用', detail: '能在写作和面谈中恰当引用诗句表达观点。' },
      { time: '三公前', keyword: '诗词信手拈来', detail: '古诗文储备成为面谈和作文的稳定加分项。' },
    ],
  },
  examTimeline: [
    {
      id: 'hanzi',
      name: '汉字小达人',
      target: '参赛',
      date: '2027.04',
      month: '三年级春季',
      registerBefore: '学校统一报名',
      notes: '考察汉字储备和书写，三年级开始可以参赛',
    },
    {
      id: 'gushihui-1',
      name: '古诗文大会（初赛）',
      target: '通过初赛',
      date: '2027.11',
      month: '四年级上',
      registerBefore: '学校统一报名',
      notes: '四年级开始系统参赛，目标进入复赛',
    },
    {
      id: 'gushihui-2',
      name: '古诗文大会（复赛）',
      target: '冲进复赛',
      date: '2027.12',
      month: '四年级上',
      registerBefore: '初赛晋级',
      notes: '复赛难度明显提升，需要文学常识积累',
    },
    {
      id: 'gushihui-3',
      name: '古诗文大会（决赛）',
      target: '决赛',
      date: '2028.03',
      month: '四年级下',
      registerBefore: '复赛晋级',
      notes: '如果能进决赛，是简历上很好的亮点',
    },
    {
      id: 'resume',
      name: '综合荣誉整理',
      target: '完整简历',
      date: '2029.04',
      month: '五年级下',
      registerBefore: '提前准备',
      notes: '三公鸡尾酒简历需要古诗文、汉字、校内荣誉、社会实践等',
    },
  ],
};

export const DEFAULT_MATH_PLAN: SubjectPlanConfigData = {
  tracks: [
    {
      id: 'school',
      name: '校内数学',
      color: '#3b82f6',
      description: '保证校内成绩，建立计算和基础能力',
    },
    {
      id: 'olympiad',
      name: '奥数体系',
      color: '#8b5cf6',
      description: '系统学习奥数七大模块，为 AMC8 打基础',
    },
    {
      id: 'exam',
      name: '竞赛证书',
      color: '#f59e0b',
      description: '袋鼠、澳洲 AMC、AMC8 等三公硬通货',
    },
  ],
  timeAxis: [
    { label: '2025 暑假', position: 0 },
    { label: '二上', position: 12 },
    { label: '二下', position: 24 },
    { label: '三上', position: 36 },
    { label: '三下', position: 48 },
    { label: '四上', position: 60 },
    { label: '四下', position: 72 },
    { label: '五上', position: 84 },
    { label: '三公', position: 100 },
  ],
  nodes: [
    {
      id: 'm-school-1',
      trackId: 'school',
      label: '二年级校内',
      position: 0,
      time: '2025.09',
      detail: '校内计算、应用题稳定 95+',
    },
    {
      id: 'm-school-2',
      trackId: 'school',
      label: '三年级校内',
      position: 25,
      time: '2026.09',
      detail: '四则运算、几何基础扎实',
    },
    {
      id: 'm-school-3',
      trackId: 'school',
      label: '四年级校内',
      position: 50,
      time: '2027.09',
      detail: '分数小数、简单方程',
    },
    {
      id: 'm-school-4',
      trackId: 'school',
      label: '五年级校内',
      position: 75,
      time: '2028.09',
      detail: '小升初复习，校内成绩保持前列',
    },
    {
      id: 'm-school-5',
      trackId: 'school',
      label: '初中衔接',
      position: 100,
      time: '2029.09',
      detail: '初中数学预习',
    },
    {
      id: 'm-olympiad-1',
      trackId: 'olympiad',
      label: '奥数启蒙',
      position: 0,
      time: '2025.09',
      detail: '计算、图形、逻辑趣味题',
    },
    {
      id: 'm-olympiad-2',
      trackId: 'olympiad',
      label: '系统奥数',
      position: 25,
      time: '2026.09',
      detail: '七大模块入门：计算、几何、数论、组合',
    },
    {
      id: 'm-olympiad-3',
      trackId: 'olympiad',
      label: '模块深入',
      position: 50,
      time: '2027.09',
      detail: '数论、组合、几何进阶',
    },
    {
      id: 'm-olympiad-4',
      trackId: 'olympiad',
      label: 'AMC8 专题',
      position: 75,
      time: '2028.09',
      detail: 'AMC8 高频考点、真题训练',
    },
    {
      id: 'm-olympiad-5',
      trackId: 'olympiad',
      label: '奥数收尾',
      position: 100,
      time: '2029.05',
      detail: '三公前保持手感',
    },
    {
      id: 'm-exam-1',
      trackId: 'exam',
      label: '袋鼠 L1/L2',
      position: 8,
      time: '2026.04',
      detail: '低年级竞赛，培养兴趣和节奏',
    },
    {
      id: 'm-exam-2',
      trackId: 'exam',
      label: '袋鼠银奖',
      position: 28,
      time: '2027.04',
      detail: '三年级袋鼠 L2 银奖',
    },
    {
      id: 'm-exam-3',
      trackId: 'exam',
      label: '澳洲 AMC B',
      position: 42,
      time: '2027.09',
      detail: '四年级澳洲 AMC，目标 Distinction',
    },
    {
      id: 'm-exam-4',
      trackId: 'exam',
      label: 'AMC8 首考',
      position: 58,
      time: '2028.01',
      detail: '四年级寒假首考 AMC8，摸底水平',
    },
    {
      id: 'm-exam-5',
      trackId: 'exam',
      label: 'AMC8 二考',
      position: 72,
      time: '2028.11',
      detail: '五年级冲 20+',
    },
    {
      id: 'm-exam-6',
      trackId: 'exam',
      label: 'AMC8 20+',
      position: 85,
      time: '2029.01',
      detail: '三公简历核心硬通货',
    },
  ],
  keyAchievements: {
    school: [
      { time: '二上期末', keyword: '计算稳定', detail: '校内计算、应用题稳定 95+' },
      { time: '三上期末', keyword: '四则运算', detail: '四则运算、几何基础扎实' },
      { time: '四上期末', keyword: '分数小数', detail: '分数小数、简单方程掌握' },
      { time: '五上期末', keyword: '校内前列', detail: '小升初复习，校内成绩保持前列' },
      { time: '三公前', keyword: '初中衔接', detail: '初中数学预习完成' },
    ],
    olympiad: [
      { time: '二上期末', keyword: '奥数启蒙', detail: '计算、图形、逻辑趣味题入门' },
      { time: '三上期末', keyword: '七大模块', detail: '七大模块入门：计算、几何、数论、组合' },
      { time: '四上期末', keyword: '模块深入', detail: '数论、组合、几何进阶' },
      { time: '五上期末', keyword: 'AMC8 专题', detail: 'AMC8 高频考点、真题训练' },
      { time: '三公前', keyword: '保持手感', detail: '三公前保持奥数解题手感' },
    ],
    exam: [
      { time: '二年级春季', keyword: '袋鼠 L1', detail: '低年级竞赛，培养兴趣和节奏' },
      { time: '三年级春季', keyword: '袋鼠银奖', detail: '三年级袋鼠 L2 银奖' },
      { time: '四年级上', keyword: '澳洲 AMC', detail: '四年级澳洲 AMC，目标 Distinction' },
      { time: '四年级寒假', keyword: 'AMC8 首考', detail: '四年级寒假首考 AMC8，摸底水平' },
      { time: '五年级上', keyword: 'AMC8 20+', detail: '五年级冲 20+' },
    ],
  },
  examTimeline: [
    {
      id: 'kangaroo-l1',
      name: '袋鼠数学 L1',
      target: '体验参赛',
      date: '2026.04',
      month: '二年级春季',
      registerBefore: '2026.03 前报名',
      notes: '一年级/二年级可参加 L1，重在培养竞赛节奏和兴趣',
    },
    {
      id: 'kangaroo-l2',
      name: '袋鼠数学 L2',
      target: '银奖',
      date: '2027.04',
      month: '三年级春季',
      registerBefore: '2027.03 前报名',
      notes: '三年级参加 L2，目标银奖以上，为简历积累竞赛经历',
    },
    {
      id: 'amc-b',
      name: '澳洲 AMC B',
      target: 'Distinction',
      date: '2027.09',
      month: '四年级上',
      registerBefore: '2027.08 前报名',
      notes: '澳洲 AMC 是 AMC8 前很好的过渡竞赛',
    },
    {
      id: 'amc8-first',
      name: 'AMC8 首考',
      target: '15+ 摸底',
      date: '2028.01',
      month: '四年级寒假',
      registerBefore: '2027.11 前报名',
      notes: 'AMC8 一年一次，首考摸底真实水平',
    },
    {
      id: 'amc8-second',
      name: 'AMC8 二考',
      target: '20+',
      date: '2028.11',
      month: '五年级上',
      registerBefore: '2028.10 前报名',
      notes: '五年级上学期是冲 20+ 的关键考期',
    },
    {
      id: 'amc8-final',
      name: 'AMC8 最终考',
      target: '20+',
      date: '2029.01',
      month: '五年级寒假',
      registerBefore: '2028.11 前报名',
      notes: '三公前最后一次 AMC8，必须拿到 20+',
    },
  ],
};

export const DEFAULT_ENGLISH_PLAN: SubjectPlanConfigData = {
  tracks: [
    {
      id: 'raz',
      name: 'RAZ 阅读线',
      color: '#10b981',
      description: '分级阅读建立阅读量和阅读速度',
    },
    {
      id: 'od',
      name: 'OD 体系线',
      color: '#8b5cf6',
      description: '系统语法、写作和综合输入输出',
    },
    {
      id: 'exam',
      name: '考证线',
      color: '#f59e0b',
      description: 'KET → PET → 小托福，三公硬通货',
    },
  ],
  timeAxis: [
    { label: '2025 暑假', position: 0 },
    { label: '2026 寒', position: 13 },
    { label: '2026 暑', position: 28 },
    { label: '2027 寒', position: 41 },
    { label: '2027 暑', position: 54 },
    { label: '2028 寒', position: 67 },
    { label: '2028 暑', position: 80 },
    { label: '2028 冬', position: 91 },
    { label: '三公', position: 100 },
  ],
  nodes: [
    {
      id: 'raz-e',
      trackId: 'raz',
      position: 0,
      label: 'RAZ E',
      detail: '当前级别，quiz 正确率偏低需强化',
      time: '2025.07',
    },
    {
      id: 'raz-g',
      trackId: 'raz',
      position: 13,
      label: 'RAZ G',
      detail: 'OD1 收尾时达到',
      time: '2026.01',
    },
    {
      id: 'raz-ij-1',
      trackId: 'raz',
      position: 28,
      label: 'RAZ I/J',
      detail: 'OD2 学完时达到',
      time: '2026.08',
    },
    {
      id: 'raz-ij-2',
      trackId: 'raz',
      position: 41,
      label: 'RAZ I/J',
      detail: 'KET 备考阶段维持',
      time: '2027.02',
    },
    {
      id: 'raz-kl-1',
      trackId: 'raz',
      position: 54,
      label: 'RAZ K/L',
      detail: 'PET 备考阶段达到',
      time: '2027.08',
    },
    {
      id: 'raz-kl-2',
      trackId: 'raz',
      position: 67,
      label: 'RAZ K/L',
      detail: 'PET/小托福衔接阶段',
      time: '2028.02',
    },
    {
      id: 'raz-kl-3',
      trackId: 'raz',
      position: 80,
      label: 'RAZ K/L',
      detail: '小托福首考阶段',
      time: '2028.08',
    },
    {
      id: 'raz-kl-4',
      trackId: 'raz',
      position: 91,
      label: 'RAZ K/L',
      detail: '小托福 850+ 维持',
      time: '2028.12',
    },
    {
      id: 'od1-u7',
      trackId: 'od',
      position: 0,
      label: 'OD1 U7',
      detail: '当前进度，四季变化单元',
      time: '2025.07',
    },
    {
      id: 'od1-u18',
      trackId: 'od',
      position: 13,
      label: 'OD1 U18',
      detail: 'OD1 全册学完',
      time: '2026.01',
    },
    {
      id: 'od2-u18',
      trackId: 'od',
      position: 28,
      label: 'OD2 U18',
      detail: 'OD2 全册学完，蓝思 350-400',
      time: '2026.08',
    },
    {
      id: 'od2-review',
      trackId: 'od',
      position: 41,
      label: 'OD2 复习',
      detail: 'KET 备考阶段复习 OD2',
      time: '2027.02',
    },
    {
      id: 'od3-u9',
      trackId: 'od',
      position: 54,
      label: 'OD3 U9',
      detail: 'OD3 前半完成',
      time: '2027.08',
    },
    {
      id: 'od3-u18',
      trackId: 'od',
      position: 67,
      label: 'OD3 U18',
      detail: 'OD3 全册学完',
      time: '2028.02',
    },
    {
      id: 'od3-end',
      trackId: 'od',
      position: 80,
      label: 'OD3 收尾',
      detail: '小托福题型适应期',
      time: '2028.08',
    },
    {
      id: 'od-maintain',
      trackId: 'od',
      position: 91,
      label: '维持',
      detail: '保持英语水平',
      time: '2028.12',
    },
    {
      id: 'exam-start',
      trackId: 'exam',
      position: 0,
      label: '起步',
      detail: 'RAZ/OD 基础阶段',
      time: '2025.07',
    },
    {
      id: 'exam-base',
      trackId: 'exam',
      position: 13,
      label: '基础',
      detail: '继续积累',
      time: '2026.01',
    },
    {
      id: 'exam-ket-prep',
      trackId: 'exam',
      position: 28,
      label: 'KET 备考',
      detail: '三年级上学期开始专项',
      time: '2026.09',
    },
    {
      id: 'exam-ket',
      trackId: 'exam',
      position: 41,
      label: 'KET 卓越',
      detail: '目标 140+',
      time: '2027.02',
    },
    {
      id: 'exam-pet-prep',
      trackId: 'exam',
      position: 54,
      label: 'PET 备考',
      detail: '三年级暑假开始',
      time: '2027.08',
    },
    {
      id: 'exam-pet',
      trackId: 'exam',
      position: 67,
      label: 'PET 卓越',
      detail: '目标 160+',
      time: '2028.02',
    },
    {
      id: 'exam-toefl-1',
      trackId: 'exam',
      position: 80,
      label: '小托福 800+',
      detail: '四年级春季首考',
      time: '2028.08',
    },
    {
      id: 'exam-toefl-2',
      trackId: 'exam',
      position: 91,
      label: '小托福 850+',
      detail: '五年级上 12 月前',
      time: '2028.12',
    },
  ],
  keyAchievements: {
    raz: [
      { time: '2026.01', keyword: 'RAZ G', detail: 'OD1 收尾时达到 RAZ G' },
      { time: '2026.08', keyword: 'RAZ I/J', detail: 'OD2 学完时达到 RAZ I/J' },
      { time: '2027.08', keyword: 'RAZ K/L', detail: 'PET 备考阶段达到 RAZ K/L' },
      { time: '2028.12', keyword: '维持 K/L', detail: '小托福 850+ 维持阅读能力' },
    ],
    od: [
      { time: '2026.01', keyword: 'OD1 完成', detail: 'OD1 全册学完' },
      { time: '2026.08', keyword: 'OD2 完成', detail: 'OD2 全册学完，蓝思 350-400' },
      { time: '2028.02', keyword: 'OD3 完成', detail: 'OD3 全册学完' },
      { time: '2028.12', keyword: 'OD 维持', detail: '小托福题型适应，保持英语水平' },
    ],
    exam: [
      { time: '2027.02', keyword: 'KET 卓越', detail: '目标 KET 卓越 140+' },
      { time: '2028.02', keyword: 'PET 卓越', detail: '目标 PET 卓越 160+' },
      { time: '2028.08', keyword: '小托福首考', detail: '小托福首考目标 800+' },
      { time: '2028.12', keyword: '小托福 850+', detail: '五年级上 12 月前小托福 850+' },
    ],
  },
  examTimeline: [
    {
      id: 'ket',
      name: 'KET',
      target: '卓越 140+',
      date: '2028.01-02',
      month: '三年级寒假',
      registerBefore: '2027.11 前联系机构代报',
      notes: 'KET 一年多次，建议三年级上学期先摸底再确定考期',
    },
    {
      id: 'pet',
      name: 'PET',
      target: '卓越 160+',
      date: '2029.01-02',
      month: '四年级寒假',
      registerBefore: '2028.11 前联系机构代报',
      notes: 'PET 卓越后，1-2 个月熟悉小托福题型即可首考',
    },
    {
      id: 'toefl-1',
      name: '小托福首考',
      target: '800+',
      date: '2029.04-05',
      month: '四年级春季',
      registerBefore: '2029.03 前报名',
      notes: '利用 PET 卓越的能力峰值，重点适应学术听力和语言形式',
    },
    {
      id: 'toefl-2',
      name: '小托福二考',
      target: '850+',
      date: '2029.10-12',
      month: '五年级上',
      registerBefore: '2029.09 前报名',
      notes: '五年级 12 月前必须拿到 850+，为三公鸡尾酒简历做准备',
    },
  ],
};

export async function seedSystemSubjectPlans(prisma: PrismaClient): Promise<number> {
  const subjects: Array<{ subject: 'chinese' | 'math' | 'english'; data: SubjectPlanConfigData }> =
    [
      { subject: 'chinese', data: DEFAULT_CHINESE_PLAN },
      { subject: 'math', data: DEFAULT_MATH_PLAN },
      { subject: 'english', data: DEFAULT_ENGLISH_PLAN },
    ];

  let seeded = 0;
  for (const { subject, data } of subjects) {
    const existingCount = await prisma.subjectPlanConfig.count({
      where: { isSystem: true, subject },
    });

    if (existingCount > 0) {
      continue;
    }

    await prisma.subjectPlanConfig.create({
      data: {
        subject,
        tracks: data.tracks as any,
        timeAxis: data.timeAxis as any,
        nodes: data.nodes as any,
        keyAchievements: data.keyAchievements as any,
        examTimeline: data.examTimeline as any,
        isSystem: true,
        userId: null,
      },
    });

    seeded += 1;
  }

  return seeded;
}
