import { PrismaClient } from './generated/prisma';
import { SubjectPlanConfigData } from './subjects/subjectPlan';

export const DEFAULT_CHINESE_PLAN: SubjectPlanConfigData = {
  tracks: [
    {
      id: 'school',
      name: '校内基础线',
      color: '#3b82f6',
      description: '跟随学校进度，用教辅巩固字词、句式、校内阅读',
    },
    {
      id: 'extensiveReading',
      name: '现代文泛读积累线',
      color: '#14b8a6',
      description: '绘本、桥梁书、儿童文学、报刊时文，积累阅读量',
    },
    {
      id: 'intensiveReading',
      name: '现代文精读线',
      color: '#8b5cf6',
      description: '整本书精读、阅读理解训练、答题规范',
    },
    {
      id: 'output',
      name: '输出表达线',
      color: '#f43f5e',
      description: '口语复述、课堂表达、自我介绍、即兴问答、写作',
    },
    {
      id: 'classical',
      name: '古文线',
      color: '#f59e0b',
      description: '小古文、文言词汇、文言文阅读',
    },
    {
      id: 'poetry',
      name: '诗词线',
      color: '#ec4899',
      description: '古诗背诵、诗词理解、古诗文大会',
    },
  ],
  timeAxis: [
    { label: '2025 暑假', position: 0 },
    { label: '一上', position: 10 },
    { label: '一下', position: 20 },
    { label: '二上', position: 30 },
    { label: '二下', position: 40 },
    { label: '三上', position: 50 },
    { label: '三下', position: 60 },
    { label: '四上', position: 70 },
    { label: '四下', position: 80 },
    { label: '五上', position: 90 },
    { label: '三公', position: 100 },
  ],
  nodes: [
    // 校内基础线
    {
      id: 'c-school-1',
      trackId: 'school',
      label: '字词巩固',
      position: 10,
      time: '2025.09',
      detail: '跟随课内进度，每天 15 分钟字词练习，夯实笔画、笔顺和常用字',
    },
    {
      id: 'c-school-2',
      trackId: 'school',
      label: '默写能手',
      position: 30,
      time: '2026.09',
      detail: '系统默写训练，错别字整理，校内基础知识不丢分',
    },
    {
      id: 'c-school-3',
      trackId: 'school',
      label: '阅读基础题',
      position: 50,
      time: '2027.09',
      detail: '掌握课内阅读理解题型，学会定位信息和规范作答',
    },
    {
      id: 'c-school-4',
      trackId: 'school',
      label: '答题规范',
      position: 70,
      time: '2028.09',
      detail: '阅读答题模板化，作文审题不跑题，校内成绩稳定优秀',
    },
    {
      id: 'c-school-5',
      trackId: 'school',
      label: '综合复习',
      position: 90,
      time: '2028.09',
      detail: '系统梳理小学语文知识点，查漏补缺，为三公鸡尾酒简历打底',
    },

    // 现代文泛读积累线
    {
      id: 'c-extensive-1',
      trackId: 'extensiveReading',
      label: '绘本/桥梁书',
      position: 10,
      time: '2025.09',
      detail: '培养阅读兴趣，每天亲子共读或自主阅读 30 分钟',
    },
    {
      id: 'c-extensive-2',
      trackId: 'extensiveReading',
      label: '儿童文学',
      position: 30,
      time: '2026.09',
      detail: '章节书、儿童文学，保持阅读量，拓宽知识面',
    },
    {
      id: 'c-extensive-3',
      trackId: 'extensiveReading',
      label: '名著 simplified',
      position: 50,
      time: '2027.09',
      detail: '选择适合年龄的名著 simplified 版，积累人文素养',
    },
    {
      id: 'c-extensive-4',
      trackId: 'extensiveReading',
      label: '报刊时文',
      position: 70,
      time: '2028.09',
      detail: '接触新闻、科普、历史类文章，为面谈积累素材',
    },
    {
      id: 'c-extensive-5',
      trackId: 'extensiveReading',
      label: '综合阅读',
      position: 90,
      time: '2028.09',
      detail: '保持高强度泛读，关注社会热点，提升信息获取能力',
    },

    // 现代文精读线
    {
      id: 'c-intensive-1',
      trackId: 'intensiveReading',
      label: '亲子共读',
      position: 10,
      time: '2025.09',
      detail: '低年级以兴趣为主，通过提问引导孩子理解故事',
    },
    {
      id: 'c-intensive-2',
      trackId: 'intensiveReading',
      label: '读书笔记',
      position: 30,
      time: '2026.09',
      detail: '学会摘抄好词好句，写简单的读后感和人物分析',
    },
    {
      id: 'c-intensive-3',
      trackId: 'intensiveReading',
      label: '精读训练',
      position: 50,
      time: '2027.09',
      detail: '阅读理解专项训练，掌握主旨、结构、修辞等答题方法',
    },
    {
      id: 'c-intensive-4',
      trackId: 'intensiveReading',
      label: '整本书精读',
      position: 70,
      time: '2028.09',
      detail: '精读 2-3 本名著，能分析人物、主题和写作手法',
    },
    {
      id: 'c-intensive-5',
      trackId: 'intensiveReading',
      label: '真题训练',
      position: 90,
      time: '2028.09',
      detail: '接触小升初真题，限时训练，提升应试阅读能力',
    },

    // 输出表达线
    {
      id: 'c-output-1',
      trackId: 'output',
      label: '看图说话',
      position: 10,
      time: '2025.09',
      detail: '能根据图片讲清楚时间、地点、人物、事件',
    },
    {
      id: 'c-output-2',
      trackId: 'output',
      label: '100字短文',
      position: 30,
      time: '2026.09',
      detail: '从看图写话过渡到短文，句子通顺、结构完整',
    },
    {
      id: 'c-output-3',
      trackId: 'output',
      label: '300字作文',
      position: 50,
      time: '2027.09',
      detail: '掌握记叙文结构，能写出有细节、有情感的作文',
    },
    {
      id: 'c-output-4',
      trackId: 'output',
      label: '观点写作',
      position: 70,
      time: '2028.09',
      detail: '能针对话题表达观点，论据清楚，逻辑有条理',
    },
    {
      id: 'c-output-5',
      trackId: 'output',
      label: '面谈表达',
      position: 100,
      time: '2029.05',
      detail: '自我介绍、即兴问答、观点表达流利自信',
    },

    // 古文线
    {
      id: 'c-classical-1',
      trackId: 'classical',
      label: '小古文启蒙',
      position: 40,
      time: '2027.02',
      detail: '接触简短小古文，培养语感，积累常见文言词汇',
    },
    {
      id: 'c-classical-2',
      trackId: 'classical',
      label: '小古文 50篇',
      position: 60,
      time: '2027.09',
      detail: '系统学习 50 篇小古文，理解词义和句式',
    },
    {
      id: 'c-classical-3',
      trackId: 'classical',
      label: '文言文阅读',
      position: 80,
      time: '2028.09',
      detail: '能独立阅读浅显文言文，掌握实词、虚词和翻译技巧',
    },
    {
      id: 'c-classical-4',
      trackId: 'classical',
      label: '古文活用',
      position: 100,
      time: '2029.05',
      detail: '能在写作和面谈中引用古文，提升表达深度',
    },

    // 诗词线
    {
      id: 'c-poetry-1',
      trackId: 'poetry',
      label: '古诗启蒙',
      position: 10,
      time: '2025.09',
      detail: '每周 1-2 首古诗，熟读成诵，感受韵律',
    },
    {
      id: 'c-poetry-2',
      trackId: 'poetry',
      label: '75+80 背诵',
      position: 30,
      time: '2026.09',
      detail: '系统背诵小学必背古诗，理解诗意和作者背景',
    },
    {
      id: 'c-poetry-3',
      trackId: 'poetry',
      label: '古诗文大会',
      position: 60,
      time: '2027.11',
      detail: '四年级开始参赛，目标进入复赛/决赛',
    },
    {
      id: 'c-poetry-4',
      trackId: 'poetry',
      label: '诗词赏析',
      position: 80,
      time: '2028.09',
      detail: '能赏析诗词的意境、手法和情感',
    },
    {
      id: 'c-poetry-5',
      trackId: 'poetry',
      label: '面谈引用',
      position: 100,
      time: '2029.05',
      detail: '能在面谈中恰当引用诗句表达观点',
    },
  ],
  yearlyTargets: {
    school: [
      {
        grade: '一年级',
        period: '2025.09 - 2026.07',
        keyword: '字词巩固',
        detail: '跟随课内进度，每天 15 分钟字词练习，夯实笔画、笔顺和常用字。',
        milestones: ['期中复习', '期末复习'],
      },
      {
        grade: '二年级',
        period: '2026.09 - 2027.07',
        keyword: '默写能手',
        detail: '系统默写训练，错别字整理，校内基础知识不丢分。',
        milestones: ['汉字小达人准备'],
      },
      {
        grade: '三年级',
        period: '2027.09 - 2028.07',
        keyword: '阅读基础题',
        detail: '掌握课内阅读理解题型，学会定位信息和规范作答。',
        milestones: ['汉字小达人参赛'],
      },
      {
        grade: '四年级',
        period: '2028.09 - 2029.07',
        keyword: '答题规范',
        detail: '阅读答题模板化，作文审题不跑题，校内成绩稳定优秀。',
        milestones: ['古诗文大会参赛'],
      },
      {
        grade: '五年级',
        period: '2029.09 - 2030.05',
        keyword: '综合复习',
        detail: '系统梳理小学语文知识点，查漏补缺，为三公鸡尾酒简历打底。',
        milestones: ['简历整理'],
      },
    ],
    extensiveReading: [
      {
        grade: '一年级',
        period: '2025.09 - 2026.07',
        keyword: '绘本/桥梁书',
        detail: '培养阅读兴趣，每天亲子共读或自主阅读 30 分钟，全年阅读量 30 本以上。',
      },
      {
        grade: '二年级',
        period: '2026.09 - 2027.07',
        keyword: '儿童文学',
        detail: '章节书、儿童文学，保持阅读量，拓宽知识面。',
      },
      {
        grade: '三年级',
        period: '2027.09 - 2028.07',
        keyword: '名著 simplified',
        detail: '选择适合年龄的名著 simplified 版，积累人文素养。',
      },
      {
        grade: '四年级',
        period: '2028.09 - 2029.07',
        keyword: '报刊时文',
        detail: '接触新闻、科普、历史类文章，为面谈积累素材。',
      },
      {
        grade: '五年级',
        period: '2029.09 - 2030.05',
        keyword: '综合阅读',
        detail: '保持高强度泛读，关注社会热点，提升信息获取能力。',
      },
    ],
    intensiveReading: [
      {
        grade: '一年级',
        period: '2025.09 - 2026.07',
        keyword: '亲子共读',
        detail: '低年级以兴趣为主，通过提问引导孩子理解故事。',
      },
      {
        grade: '二年级',
        period: '2026.09 - 2027.07',
        keyword: '读书笔记',
        detail: '学会摘抄好词好句，写简单的读后感和人物分析。',
      },
      {
        grade: '三年级',
        period: '2027.09 - 2028.07',
        keyword: '精读训练',
        detail: '阅读理解专项训练，掌握主旨、结构、修辞等答题方法。',
      },
      {
        grade: '四年级',
        period: '2028.09 - 2029.07',
        keyword: '整本书精读',
        detail: '精读 2-3 本名著，能分析人物、主题和写作手法。',
      },
      {
        grade: '五年级',
        period: '2029.09 - 2030.05',
        keyword: '真题训练',
        detail: '接触小升初真题，限时训练，提升应试阅读能力。',
      },
    ],
    output: [
      {
        grade: '一年级',
        period: '2025.09 - 2026.07',
        keyword: '看图说话',
        detail: '能根据图片讲清楚时间、地点、人物、事件。',
      },
      {
        grade: '二年级',
        period: '2026.09 - 2027.07',
        keyword: '100字短文',
        detail: '从看图写话过渡到短文，句子通顺、结构完整。',
      },
      {
        grade: '三年级',
        period: '2027.09 - 2028.07',
        keyword: '300字作文',
        detail: '掌握记叙文结构，能写出有细节、有情感的作文。',
      },
      {
        grade: '四年级',
        period: '2028.09 - 2029.07',
        keyword: '观点写作',
        detail: '能针对话题表达观点，论据清楚，逻辑有条理。',
      },
      {
        grade: '五年级',
        period: '2029.09 - 2030.05',
        keyword: '面谈表达',
        detail: '自我介绍、即兴问答、观点表达流利自信。',
        milestones: ['模拟面谈'],
      },
    ],
    classical: [
      {
        grade: '一年级',
        period: '2025.09 - 2026.07',
        keyword: '—',
        detail: '一年级不单独开设古文线，以古诗启蒙为主。',
      },
      {
        grade: '二年级',
        period: '2026.09 - 2027.07',
        keyword: '小古文启蒙',
        detail: '接触简短小古文，培养语感，积累常见文言词汇。',
      },
      {
        grade: '三年级',
        period: '2027.09 - 2028.07',
        keyword: '小古文 50篇',
        detail: '系统学习 50 篇小古文，理解词义和句式。',
      },
      {
        grade: '四年级',
        period: '2028.09 - 2029.07',
        keyword: '文言文阅读',
        detail: '能独立阅读浅显文言文，掌握实词、虚词和翻译技巧。',
      },
      {
        grade: '五年级',
        period: '2029.09 - 2030.05',
        keyword: '古文活用',
        detail: '能在写作和面谈中引用古文，提升表达深度。',
      },
    ],
    poetry: [
      {
        grade: '一年级',
        period: '2025.09 - 2026.07',
        keyword: '古诗启蒙',
        detail: '每周 1-2 首古诗，熟读成诵，全年积累 30 首左右。',
      },
      {
        grade: '二年级',
        period: '2026.09 - 2027.07',
        keyword: '75+80 背诵',
        detail: '系统背诵小学必背古诗，理解诗意和作者背景。',
      },
      {
        grade: '三年级',
        period: '2027.09 - 2028.07',
        keyword: '诗词理解',
        detail: '能简单赏析诗词意境，了解作者和创作背景。',
        milestones: ['古诗文大会初赛准备'],
      },
      {
        grade: '四年级',
        period: '2028.09 - 2029.07',
        keyword: '古诗文大会',
        detail: '参赛并冲刺复赛，积累文学常识。',
        milestones: ['古诗文大会初赛', '古诗文大会复赛'],
      },
      {
        grade: '五年级',
        period: '2029.09 - 2030.05',
        keyword: '面谈引用',
        detail: '能在面谈中恰当引用诗句表达观点。',
      },
    ],
  },
  examTimeline: [
    {
      id: 'hanzi',
      name: '汉字小达人',
      target: '参赛',
      date: '2027.04',
      month: '三年级春季',
      registerBefore: '学校统一报名',
      notes: '考察汉字储备和书写，三年级开始可以参赛',
    },
    {
      id: 'gushihui-1',
      name: '古诗文大会（初赛）',
      target: '通过初赛',
      date: '2027.11',
      month: '四年级上',
      registerBefore: '学校统一报名',
      notes: '四年级开始系统参赛，目标进入复赛',
    },
    {
      id: 'gushihui-2',
      name: '古诗文大会（复赛）',
      target: '冲进复赛',
      date: '2027.12',
      month: '四年级上',
      registerBefore: '初赛晋级',
      notes: '复赛难度明显提升，需要文学常识积累',
    },
    {
      id: 'gushihui-3',
      name: '古诗文大会（决赛）',
      target: '决赛',
      date: '2028.03',
      month: '四年级下',
      registerBefore: '复赛晋级',
      notes: '如果能进决赛，是简历上很好的亮点',
    },
    {
      id: 'resume',
      name: '综合荣誉整理',
      target: '完整简历',
      date: '2029.04',
      month: '五年级下',
      registerBefore: '提前准备',
      notes: '三公鸡尾酒简历需要古诗文、汉字、校内荣誉、社会实践等',
    },
  ],
};

export async function seedSystemSubjectPlans(prisma: PrismaClient): Promise<number> {
  const existingCount = await prisma.subjectPlanConfig.count({
    where: { isSystem: true, subject: 'chinese' },
  });

  if (existingCount > 0) {
    return 0;
  }

  await prisma.subjectPlanConfig.create({
    data: {
      subject: 'chinese',
      tracks: DEFAULT_CHINESE_PLAN.tracks as any,
      timeAxis: DEFAULT_CHINESE_PLAN.timeAxis as any,
      nodes: DEFAULT_CHINESE_PLAN.nodes as any,
      yearlyTargets: DEFAULT_CHINESE_PLAN.yearlyTargets as any,
      examTimeline: DEFAULT_CHINESE_PLAN.examTimeline as any,
      isSystem: true,
      userId: null,
    },
  });

  return 1;
}
