import { TaskAlignment, TaskCategory, TaskTemplate } from './storage.types';

export type SystemTaskTemplate = Omit<TaskTemplate, 'id' | 'userId' | 'createdAt' | 'updatedAt'> & {
  id: string;
};

export const TASK_CATEGORY_LABELS: Record<TaskCategory, string> = {
  chinese: '语文',
  math: '数学',
  english: '英语',
  school: '学校作业',
  reading: '阅读',
  sport: '运动',
  interest: '兴趣班',
  other: '其他',
};

export const TASK_CATEGORY_ICONS: Record<TaskCategory, string> = {
  chinese: '📖',
  math: '🔢',
  english: '🔤',
  school: '🎒',
  reading: '📚',
  sport: '🏃',
  interest: '🎨',
  other: '📝',
};

export const TASK_CATEGORY_COLORS: Record<TaskCategory, string> = {
  chinese: 'text-rose-400 bg-rose-400/10',
  math: 'text-cyan-400 bg-cyan-400/10',
  english: 'text-amber-400 bg-amber-400/10',
  school: 'text-emerald-400 bg-emerald-400/10',
  reading: 'text-violet-400 bg-violet-400/10',
  sport: 'text-orange-400 bg-orange-400/10',
  interest: 'text-pink-400 bg-pink-400/10',
  other: 'text-slate-400 bg-slate-400/10',
};

export const TASK_ALIGNMENT_LABELS: Record<TaskAlignment, string> = {
  ahead: '提前准备',
  ontrack: '当前阶段',
  behind: '需要补差',
  optional: '可选拓展',
  unrelated: '不相关',
};

export const SYSTEM_TASK_TEMPLATES: SystemTaskTemplate[] = [
  // 通用基础
  {
    id: 'tpl-school-homework',
    title: '完成学校作业',
    category: 'school',
    gradeMin: 1,
    gradeMax: 12,
    duration: '60分钟',
    materials: ['学校课本', '作业本'],
    description: '完成当天学校布置的各科作业，保证质量',
    routeTags: [],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-school-review',
    title: '复习学校当天课程',
    category: 'school',
    gradeMin: 1,
    gradeMax: 12,
    duration: '30分钟',
    materials: ['课本', '课堂笔记'],
    description: '回顾当天课堂重点，整理错题和疑问',
    routeTags: [],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-reading-30',
    title: '课外阅读',
    category: 'reading',
    gradeMin: 1,
    gradeMax: 12,
    duration: '30分钟',
    materials: ['课外书', '阅读记录本'],
    description: '阅读课外书籍，做好摘抄和感想',
    routeTags: [],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sport-30',
    title: '运动锻炼',
    category: 'sport',
    gradeMin: 1,
    gradeMax: 12,
    duration: '30分钟',
    materials: ['运动鞋', '跳绳/球类'],
    description: '进行有氧运动或体能训练，增强体质',
    routeTags: [],
    source: 'system',
    isActive: true,
  },

  // 三公路线 - 语文
  {
    id: 'tpl-sg-chinese-gushi',
    title: '古诗文背诵积累',
    category: 'chinese',
    gradeMin: 1,
    gradeMax: 5,
    duration: '20分钟',
    materials: ['古诗文读本', '背诵打卡表'],
    description: '背诵1-2首古诗或古文段落，理解大意',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    milestoneTag: '古诗文大会',
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sg-chinese-reading',
    title: '三公语文阅读理解',
    category: 'chinese',
    gradeMin: 3,
    gradeMax: 5,
    duration: '40分钟',
    materials: ['阅读理解真题', '错题本'],
    description: '完成1篇三公/民办校风格的阅读理解练习',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sg-chinese-composition',
    title: '小作文/随笔练习',
    category: 'chinese',
    gradeMin: 2,
    gradeMax: 5,
    duration: '30分钟',
    materials: ['作文本', '好词好句本'],
    description: '完成300字左右的小作文或日记',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    source: 'system',
    isActive: true,
  },

  // 三公路线 - 数学
  {
    id: 'tpl-sg-math-thinking',
    title: '数学思维训练',
    category: 'math',
    gradeMin: 1,
    gradeMax: 5,
    duration: '40分钟',
    materials: ['思维训练题', '草稿纸'],
    description: '完成5-10道奥数/思维训练题',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    milestoneTag: 'AMC8',
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sg-math-amc8',
    title: 'AMC8 真题/模拟',
    category: 'math',
    gradeMin: 4,
    gradeMax: 5,
    duration: '60分钟',
    materials: ['AMC8 真题', '计时器'],
    description: '完成1套 AMC8 真题或模拟题，限时训练',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    milestoneTag: 'AMC8',
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sg-math-calc',
    title: '计算能力训练',
    category: 'math',
    gradeMin: 1,
    gradeMax: 5,
    duration: '15分钟',
    materials: ['口算题卡'],
    description: '限时完成计算练习，提高准确率和速度',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    source: 'system',
    isActive: true,
  },

  // 三公路线 - 英语
  {
    id: 'tpl-sg-english-vocab',
    title: '英语词汇积累',
    category: 'english',
    gradeMin: 1,
    gradeMax: 5,
    duration: '20分钟',
    materials: ['词汇书', '单词APP'],
    description: '背诵并复习10-20个核心词汇',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    milestoneTag: 'KET',
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sg-english-reading',
    title: '英语阅读理解',
    category: 'english',
    gradeMin: 2,
    gradeMax: 5,
    duration: '30分钟',
    materials: ['RAZ/原版读物', '阅读理解练习'],
    description: '完成1-2篇英语阅读理解或分级阅读',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    milestoneTag: 'PET',
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sg-english-listening',
    title: '英语听力训练',
    category: 'english',
    gradeMin: 1,
    gradeMax: 5,
    duration: '20分钟',
    materials: ['听力材料', '耳机'],
    description: '完成听力练习或听读原版音频',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sg-english-toefl-junior',
    title: '小托福 TOEFL Junior 练习',
    category: 'english',
    gradeMin: 4,
    gradeMax: 5,
    duration: '60分钟',
    materials: ['小托福真题', '听力材料'],
    description: '完成1套小托福听力/阅读/语法练习',
    routeTags: ['sanchu_gongban', 'sanchu_guoji'],
    milestoneTag: 'TOEFL Junior',
    source: 'system',
    isActive: true,
  },

  // 三公路线 - 综合
  {
    id: 'tpl-sg-kechuang',
    title: '科创/编程兴趣',
    category: 'interest',
    gradeMin: 2,
    gradeMax: 5,
    duration: '45分钟',
    materials: ['编程平台', '科创材料'],
    description: '进行编程、机器人或科创项目练习',
    routeTags: ['sanchu_gongban', 'sanchu_guoji'],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-sg-interview',
    title: '表达能力/面试准备',
    category: 'other',
    gradeMin: 4,
    gradeMax: 5,
    duration: '30分钟',
    materials: ['自我介绍稿', '时事素材'],
    description: '练习自我介绍、口语表达和简单问答',
    routeTags: ['sanchu_gongban', 'sanchu_minban', 'sanchu_guoji'],
    source: 'system',
    isActive: true,
  },

  // 中考路线 - 语文
  {
    id: 'tpl-zk-chinese-basic',
    title: '中考语文基础积累',
    category: 'chinese',
    gradeMin: 6,
    gradeMax: 9,
    duration: '30分钟',
    materials: ['中考语文基础手册', '错题本'],
    description: '字音字形、成语、文言文实词虚词积累',
    routeTags: ['zhongkao_putong', 'zhongkao_tese'],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-zk-chinese-composition',
    title: '中考作文素材积累',
    category: 'chinese',
    gradeMin: 6,
    gradeMax: 9,
    duration: '30分钟',
    materials: ['作文素材本', '优秀范文'],
    description: '整理作文素材，仿写段落或列提纲',
    routeTags: ['zhongkao_putong', 'zhongkao_tese'],
    source: 'system',
    isActive: true,
  },

  // 中考路线 - 数学
  {
    id: 'tpl-zk-math-basic',
    title: '中考数学基础过关',
    category: 'math',
    gradeMin: 6,
    gradeMax: 9,
    duration: '40分钟',
    materials: ['中考数学分类汇编', '错题本'],
    description: '按专题完成基础题，确保概念清晰',
    routeTags: ['zhongkao_putong', 'zhongkao_tese'],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-zk-math-zhongya',
    title: '中考压轴题训练',
    category: 'math',
    gradeMin: 8,
    gradeMax: 9,
    duration: '45分钟',
    materials: ['压轴题专项', '草稿纸'],
    description: '完成1-2道中考压轴题，总结解题方法',
    routeTags: ['zhongkao_putong', 'zhongkao_tese'],
    source: 'system',
    isActive: true,
  },

  // 中考路线 - 英语
  {
    id: 'tpl-zk-english-vocab',
    title: '中考考纲词汇',
    category: 'english',
    gradeMin: 6,
    gradeMax: 9,
    duration: '20分钟',
    materials: ['考纲词汇书', '单词卡片'],
    description: '背诵并复习中考核心词汇',
    routeTags: ['zhongkao_putong', 'zhongkao_tese'],
    source: 'system',
    isActive: true,
  },
  {
    id: 'tpl-zk-english-listening',
    title: '中考听力模拟',
    category: 'english',
    gradeMin: 7,
    gradeMax: 9,
    duration: '25分钟',
    materials: ['中考听力真题', '耳机'],
    description: '完成1套中考听力模拟题',
    routeTags: ['zhongkao_putong', 'zhongkao_tese'],
    source: 'system',
    isActive: true,
  },

  // 中考路线 - 体育/综评
  {
    id: 'tpl-zk-sport-exam',
    title: '中考体育项目训练',
    category: 'sport',
    gradeMin: 6,
    gradeMax: 9,
    duration: '45分钟',
    materials: ['运动器材'],
    description: '针对中考体育选项进行专项训练',
    routeTags: ['zhongkao_putong', 'zhongkao_tese'],
    source: 'system',
    isActive: true,
  },

  // 公办对口/摇号缓冲
  {
    id: 'tpl-gongban-prep',
    title: '校内知识预习',
    category: 'school',
    gradeMin: 1,
    gradeMax: 12,
    duration: '30分钟',
    materials: ['课本', '练习册'],
    description: '提前预习下周校内课程，减轻课堂压力',
    routeTags: ['gongban_duikou'],
    source: 'system',
    isActive: true,
  },
];

export function getSystemTaskTemplateById(id: string): SystemTaskTemplate | undefined {
  return SYSTEM_TASK_TEMPLATES.find((t) => t.id === id);
}

export function getSystemTaskTemplatesByRoute(routeId?: string): SystemTaskTemplate[] {
  if (!routeId) return SYSTEM_TASK_TEMPLATES.filter((t) => t.routeTags.length === 0);
  return SYSTEM_TASK_TEMPLATES.filter(
    (t) => t.routeTags.length === 0 || t.routeTags.includes(routeId)
  );
}
